export const sqlChallenges = [
  {
    id: "active-clients",
    title: "Активные клиенты",
    category: "SELECT",
    level: "Лёгкая",
    minutes: 7,
    description: "Выведите имена активных клиентов и дату их регистрации.",
    starter: "SELECT\n  -- выберите нужные поля\nFROM clients\nWHERE status = 'active';",
    referenceQuery: "SELECT name, registered_at FROM clients WHERE status = 'active';",
    ordered: false,
    hint: "Добавьте name и registered_at после SELECT — условие WHERE уже на месте.",
  },
  {
    id: "unique-currencies",
    title: "Уникальные валюты",
    category: "DISTINCT",
    level: "Лёгкая",
    minutes: 8,
    description: "Узнайте, в каких валютах проводились операции.",
    starter: "SELECT currency\nFROM transactions;",
    referenceQuery: "SELECT DISTINCT currency FROM transactions;",
    ordered: false,
    hint: "Используйте DISTINCT перед названием столбца, иначе валюты будут повторяться.",
  },
  {
    id: "large-transfers",
    title: "Крупные переводы",
    category: "WHERE",
    level: "Лёгкая",
    minutes: 10,
    description: "Найдите завершённые операции на сумму больше 100 000.",
    starter: "SELECT id, amount, status\nFROM transactions\nWHERE -- добавьте условия;",
    referenceQuery: "SELECT id, amount, status FROM transactions WHERE amount > 100000 AND status = 'completed';",
    ordered: false,
    hint: "Соедините два условия оператором AND: amount > 100000 и status = 'completed'.",
  },
  {
    id: "monthly-turnover",
    title: "Оборот по месяцам",
    category: "GROUP BY",
    level: "Средняя",
    minutes: 16,
    description: "Посчитайте сумму операций для каждого месяца.",
    starter: "SELECT substr(created_at, 1, 7) AS month, SUM(amount) AS turnover\nFROM transactions\n-- сгруппируйте результат",
    referenceQuery: "SELECT substr(created_at, 1, 7) AS month, SUM(amount) AS turnover FROM transactions GROUP BY month;",
    ordered: false,
    hint: "Группировка должна использовать то же выражение, что и в SELECT — substr(created_at, 1, 7).",
  },
  {
    id: "client-balance",
    title: "Клиенты и балансы",
    category: "JOIN",
    level: "Средняя",
    minutes: 18,
    description: "Соедините клиентов с их кошельками и покажите баланс.",
    starter: "SELECT c.name, w.balance\nFROM clients c\n-- соедините wallets w",
    referenceQuery: "SELECT c.name, w.balance FROM clients c JOIN wallets w ON c.id = w.client_id;",
    ordered: false,
    hint: "Свяжите таблицы по client_id: JOIN wallets w ON c.id = w.client_id.",
  },
  {
    id: "clients-without-wallet",
    title: "Клиенты без кошелька",
    category: "JOIN",
    level: "Средняя",
    minutes: 20,
    description: "Найдите клиентов, которым ещё не создан кошелёк.",
    starter: "SELECT c.id, c.name\nFROM clients c\n-- сохраните строки без совпадения",
    referenceQuery: "SELECT c.id, c.name FROM clients c LEFT JOIN wallets w ON c.id = w.client_id WHERE w.id IS NULL;",
    ordered: false,
    hint: "LEFT JOIN сохранит всех клиентов, а WHERE w.id IS NULL оставит только тех, у кого нет кошелька.",
  },
  {
    id: "risk-segments",
    title: "Риск-сегменты",
    category: "CASE",
    level: "Средняя",
    minutes: 17,
    description: "Разделите операции на low, medium и high risk по сумме.",
    starter: "SELECT id, amount,\n  -- добавьте CASE\nFROM transactions;",
    referenceQuery: "SELECT id, amount, CASE WHEN amount < 20000 THEN 'low' WHEN amount < 150000 THEN 'medium' ELSE 'high' END AS risk FROM transactions;",
    ordered: false,
    hint: "CASE WHEN amount < 20000 THEN 'low' WHEN amount < 150000 THEN 'medium' ELSE 'high' END.",
  },
  {
    id: "top-merchants",
    title: "Топ мерчантов",
    category: "HAVING",
    level: "Сложная",
    minutes: 24,
    description: "Найдите мерчантов с оборотом больше 1 000 000 и минимум 10 операциями.",
    starter: "SELECT merchant_id, SUM(amount), COUNT(*)\nFROM transactions\nGROUP BY merchant_id\n-- отфильтруйте группы",
    referenceQuery: "SELECT merchant_id, SUM(amount), COUNT(*) FROM transactions GROUP BY merchant_id HAVING SUM(amount) > 1000000 AND COUNT(*) >= 10;",
    ordered: false,
    hint: "Условия для агрегатов пишутся после GROUP BY в HAVING, а не в WHERE.",
  },
  {
    id: "retention-cohorts",
    title: "Когорты по регистрации",
    category: "CTE",
    level: "Сложная",
    minutes: 30,
    description: "Для каждого месяца регистрации посчитайте число клиентов, которые хотя бы раз совершили операцию.",
    starter: "-- начните с when: WITH cohorts AS (...)\nSELECT * FROM clients;",
    referenceQuery: "WITH cohorts AS (SELECT id, substr(registered_at, 1, 7) AS cohort_month FROM clients) SELECT cohort_month, COUNT(DISTINCT t.client_id) AS active_clients FROM cohorts c LEFT JOIN transactions t ON t.client_id = c.id GROUP BY cohort_month;",
    ordered: false,
    hint: "Начните с WITH cohorts AS (SELECT id, substr(registered_at, 1, 7) AS cohort_month FROM clients), затем присоедините transactions.",
  },
];

export const getSqlChallenge = (id) => sqlChallenges.find((item) => item.id === id) || sqlChallenges[0];
