import { useMemo, useState } from "react";
import {
  ArrowLeft, ArrowRight, CheckCircle, Code, FilePy,
  MagnifyingGlass, Play, ShieldCheck, SlidersHorizontal, Stack,
} from "@phosphor-icons/react";
import "../styles-sql.css";

export const pythonModules = [
  { n: "01", title: "Старт и базовый синтаксис", text: "Настройте Python, запустите первую программу и освойте переменные.", topics: ["Среда и первый запуск", "Переменные", "Числа и строки", "Ввод и вывод", "Функции"] },
  { n: "02", title: "Условия и циклы", text: "Научите программу принимать решения и обрабатывать последовательности.", topics: ["Условия if", "Булева логика", "Цикл for", "Цикл while", "range и enumerate"] },
  { n: "03", title: "Коллекции данных", text: "Работайте со списками, словарями, кортежами и множествами.", topics: ["Списки", "Словари", "Кортежи", "Множества", "Генераторы коллекций"] },
  { n: "04", title: "Файлы, модули и ошибки", text: "Разделяйте код, сохраняйте данные и спокойно обрабатывайте сбои.", topics: ["Импорт и модули", "Текстовые файлы", "JSON и CSV", "Исключения", "pip и зависимости"] },
  { n: "05", title: "Объектный подход", text: "Описывайте предметную область через классы и понятные контракты.", topics: ["Классы и объекты", "Атрибуты и методы", "Наследование", "Инкапсуляция", "Аннотации типов"] },
  { n: "06", title: "Проект: сервис отчётов", text: "Соберите CLI-сервис, который очищает данные и формирует отчёт.", topics: ["Бриф команды", "Декомпозиция", "Реализация", "Тесты", "README и релиз"] },
];

export const pythonChallenges = [
  { id: "clean-name", title: "Нормализация имени", category: "Строки", level: "Лёгкая", minutes: 7, description: "Очистите пробелы и приведите имя клиента к аккуратному виду.", starter: "def clean_name(value: str) -> str:\n    # ваш код\n    return value", token: ".strip()", hint: "Сначала используйте strip(), затем title().", result: "Искандер Ахунов" },
  { id: "transaction-fee", title: "Комиссия операции", category: "Условия", level: "Лёгкая", minutes: 9, description: "Рассчитайте комиссию с учётом минимального значения.", starter: "def fee(amount: float) -> float:\n    # ваш код\n    return 0", token: "max(", hint: "Функция max поможет выбрать процент или минимальную комиссию.", result: "125.0" },
  { id: "positive-total", title: "Сумма пополнений", category: "Списки", level: "Лёгкая", minutes: 10, description: "Сложите только положительные операции из списка.", starter: "def deposits(values: list[int]) -> int:\n    # ваш код\n    return 0", token: "sum(", hint: "Передайте в sum генератор с условием value > 0.", result: "48200" },
  { id: "currency-counter", title: "Счётчик валют", category: "Словари", level: "Средняя", minutes: 14, description: "Посчитайте количество операций в каждой валюте.", starter: "def count_currencies(items: list[str]) -> dict[str, int]:\n    result = {}\n    # ваш код\n    return result", token: ".get(", hint: "Получайте текущее значение через dict.get(key, 0).", result: "{'BTC': 3, 'ETH': 2, 'USDT': 4}" },
  { id: "parse-records", title: "Разбор JSON-операций", category: "JSON", level: "Средняя", minutes: 17, description: "Прочитайте JSON и верните только валидные операции.", starter: "import json\n\ndef parse_records(raw: str) -> list[dict]:\n    # ваш код\n    return []", token: "json.loads", hint: "Используйте json.loads и перехватите JSONDecodeError.", result: "3 валидные операции" },
  { id: "safe-rate", title: "Безопасный курс валют", category: "Ошибки", level: "Средняя", minutes: 16, description: "Обработайте отсутствие курса без падения отчёта.", starter: "def convert(amount: float, rates: dict, currency: str) -> float:\n    # ваш код\n    return 0", token: "raise", hint: "Явно проверьте наличие валюты и поднимите ValueError.", result: "ValueError: unknown currency" },
  { id: "wallet-class", title: "Модель кошелька", category: "Классы", level: "Средняя", minutes: 20, description: "Создайте класс кошелька с пополнением и проверкой баланса.", starter: "class Wallet:\n    def __init__(self, balance: int = 0):\n        # ваш код\n        pass", token: "self.balance", hint: "Сохраните balance в экземпляре и добавьте метод deposit.", result: "Wallet(balance=1500)" },
  { id: "report-pipeline", title: "Конвейер отчёта", category: "Функции", level: "Сложная", minutes: 26, description: "Свяжите очистку, группировку и форматирование данных.", starter: "def build_report(rows: list[dict]) -> str:\n    # ваш код\n    return ''", token: "sorted(", hint: "Разделите решение на маленькие функции и отсортируйте итог.", result: "Отчёт сформирован · 4 категории" },
  { id: "csv-summary", title: "Сводка из CSV", category: "Файлы", level: "Сложная", minutes: 28, description: "Прочитайте CSV-поток и соберите итог без загрузки всего файла в память.", starter: "import csv\n\ndef summarize(stream) -> dict:\n    # ваш код\n    return {}", token: "csv.DictReader", hint: "Итерируйтесь по csv.DictReader построчно.", result: "12 540 строк обработано" },
];

export const getPythonChallenge = (id) => pythonChallenges.find((item) => item.id === id) || pythonChallenges[0];

function PythonContextNav({ navigate, active }) {
  return <nav className="course-context-nav python-context" aria-label="Разделы курса Python"><button onClick={() => navigate("/")}><ArrowLeft size={16}/> Все направления</button><div><button className={active === "course" ? "active" : ""} onClick={() => navigate("/python")}>Курс Python</button><button className={active === "practice" ? "active" : ""} onClick={() => navigate("/python/practice")}>Практика</button></div></nav>;
}

export function PythonCoursePage({ navigate }) {
  const [open, setOpen] = useState("01");
  return <main className="sql-course-shell python-course-shell"><PythonContextNav navigate={navigate} active="course"/><section className="sql-course-hero container"><div><p className="academy-kicker">КУРС · PYTHON ДЛЯ РАБОТЫ</p><h1>Автоматизируйте задачи и собирайте полезные инструменты</h1><p>Освойте Python через небольшие рабочие сценарии Bit Tech: обработку данных, отчёты и надёжный CLI-сервис.</p><div className="sql-hero-actions"><button onClick={() => navigate("/python/practice/clean-name")}>Начать первый урок <ArrowRight size={17}/></button><button onClick={() => navigate("/python/practice")}>Открыть тренажёр</button></div></div><aside><FilePy size={42}/><small>РЕЗУЛЬТАТ КУРСА</small><h2>30 уроков · 45 задач · 1 проект</h2><ul><li>Синтаксис Python</li><li>Коллекции и файлы</li><li>Классы и тесты</li><li>Проект в GitHub</li></ul></aside></section>
  <section className="sql-workflow container"><div><Stack size={23}/><b>Получаете рабочий сценарий</b><p>Понимаете входные данные и ожидаемый результат.</p></div><div><Code size={23}/><b>Пишете код самостоятельно</b><p>Закрепляете короткую теорию в тренажёре.</p></div><div><ShieldCheck size={23}/><b>Проверяете и объясняете</b><p>Запускаете тесты и готовите код к ревью.</p></div></section>
  <section className="sql-program container"><header><div><p className="academy-kicker">ПРОГРАММА</p><h2>От первой функции до полезного сервиса</h2></div><button onClick={() => navigate("/python/practice")}>45 задач в практике <ArrowRight size={16}/></button></header><div>{pythonModules.map((module) => <article className={open === module.n ? "open" : ""} key={module.n}><button onClick={() => setOpen(open === module.n ? "" : module.n)}><span>{module.n}</span><div><h3>{module.title}</h3><p>{module.text}</p></div><b>{module.topics.length} тем</b><ArrowRight size={19}/></button>{open === module.n && <ol>{module.topics.map((topic, index) => <li key={topic}><span>{String(index + 1).padStart(2, "0")}</span><b>{topic}</b><small>урок + практика</small></li>)}</ol>}</article>)}</div></section>
  <section className="sql-final container"><FilePy size={31}/><div><small>ФИНАЛЬНЫЙ ПРОЕКТ</small><h2>Сервис подготовки отчётов</h2><p>Примите данные из CSV, проверьте их, сформируйте сводку и опубликуйте CLI-приложение в GitHub.</p></div><button onClick={() => navigate("/python/practice")}>Начать с практики <ArrowRight size={17}/></button></section></main>;
}

export function PythonTrainer({ navigate }) {
  const [query, setQuery] = useState(""); const [level, setLevel] = useState("Все"); const [category, setCategory] = useState("Все");
  const categories = ["Все", ...new Set(pythonChallenges.map((item) => item.category))];
  const filtered = useMemo(() => pythonChallenges.filter((item) => (level === "Все" || item.level === level) && (category === "Все" || item.category === category) && item.title.toLowerCase().includes(query.toLowerCase())), [query, level, category]);
  return <main className="go-practice-shell python-practice-shell"><PythonContextNav navigate={navigate} active="practice"/><div className="go-trainer container"><header className="go-trainer-header"><div><p className="academy-kicker">ПРАКТИКА · PYTHON</p><h1>Python-тренажёр</h1><p>Короткие задачи от строк и списков до файлов, классов и рабочего конвейера.</p></div><div className="trainer-progress-note"><CheckCircle size={20}/><span><b>Практика курса</b><small>Упражнения готовят к итоговому сервису, а не существуют отдельно.</small></span></div></header><section className="go-trainer-filters"><div className="trainer-filter-row"><div className="trainer-levels">{["Все", "Лёгкая", "Средняя", "Сложная"].map((item) => <button className={level === item ? "active" : ""} onClick={() => setLevel(item)} key={item}>{item}</button>)}</div><label><MagnifyingGlass size={18}/><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Поиск Python-задачи"/></label></div><div className="trainer-categories"><SlidersHorizontal size={17}/>{categories.map((item) => <button onClick={() => setCategory(item)} className={category === item ? "active" : ""} key={item}>{item}</button>)}</div></section><section className="go-task-list">{filtered.map((item, index) => <button onClick={() => navigate(`/python/practice/${item.id}`)} key={item.id}><span className={`academy-dot level-${item.level}`}/><b>{String(index + 1).padStart(2, "0")}. {item.title}</b><em>{item.category}</em><small>{item.level} · {item.minutes} мин</small><ArrowRight size={18}/></button>)}</section></div></main>;
}

export function PythonTask({ challengeId, navigate }) {
  const challenge = getPythonChallenge(challengeId); const [code, setCode] = useState(challenge.starter); const [state, setState] = useState("idle");
  const run = () => setState(code.includes(challenge.token) ? "success" : "error");
  return <main className="sql-task-shell python-task-shell"><header><button onClick={() => navigate("/python/practice")}><ArrowLeft size={17}/> Все задачи</button><span>Python · 3.13</span><button onClick={() => navigate("/python")}>Программа курса</button></header><div className="sql-task-grid"><section className="sql-task-brief"><p className="academy-kicker">{challenge.level.toUpperCase()} · {challenge.minutes} МИН</p><h1>{challenge.title}</h1><p>{challenge.description}</p><div className="python-tests"><small>АВТОПРОВЕРКА</small><b>Обычный сценарий</b><span>Проверяет ожидаемый результат</span><b>Граничный сценарий</b><span>Проверяет пустые и ошибочные данные</span><b>Читаемость</b><span>Сохраняет публичный контракт функции</span></div><button onClick={() => setState("hint")}>Показать подсказку</button>{state === "hint" && <aside>{challenge.hint}</aside>}</section><section className="sql-editor"><div className="sql-editor-top"><b>solution.py</b><span>Учебная среда Godemy</span></div><textarea value={code} onChange={(event) => { setCode(event.target.value); setState("idle"); }} spellCheck="false" aria-label="Редактор Python-кода"/><div className="sql-runbar"><button onClick={() => setCode(challenge.starter)}>Сбросить</button><button onClick={run}><Play size={15} weight="fill"/> Запустить тесты</button></div><div className={`sql-result ${state}`}><header><b>Результат</b><span>{state === "success" ? "3 проверки" : "Консоль"}</span></header>{state === "success" ? <div className="python-test-result"><p>✓ Базовый сценарий пройден</p><p>✓ Граничный сценарий пройден</p><p>✓ Результат: {challenge.result}</p></div> : <p>{state === "error" ? `Проверка пока не пройдена. ${challenge.hint}` : "Запустите тесты, чтобы проверить решение."}</p>}</div></section></div></main>;
}
